import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FEFEFE',
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  tabScrollContainer: {
    marginBottom: 30,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#FEFEFE',
    borderRadius: 16,
    padding: 4,
    shadowColor: '#201E1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f5f5f5',
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    borderRadius: 12,
    marginHorizontal: 2,
    minWidth: 80,
  },
  activeTab: {
    backgroundColor: '#EE436E',
    shadowColor: '#EE436E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  tabText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#201E1E',
    textAlign: 'center',
    opacity: 0.7,
  },
  activeTabText: {
    color: '#FEFEFE',
    fontWeight: '700',
    opacity: 1,
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 25,
    textAlign: 'center',
    color: '#201E1E',
    letterSpacing: -0.5,
  },

  table: {
    backgroundColor: '#FEFEFE',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#201E1E',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f5f5f5',
  },
  rowHeader: {
    flexDirection: 'row',
    backgroundColor: '#201E1E',
    paddingVertical: 16,
    paddingHorizontal: 12,
  },
  row: {
    flexDirection: 'row',
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f8f8f8',
  },
  headerText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    color: '#FEFEFE',
    letterSpacing: 0.5,
  },

  perifareContainer: {
    backgroundColor: '#FEFEFE',
    borderRadius: 20,
    padding: 32,
    margin: 8,
    alignItems: 'center',
    shadowColor: '#201E1E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#f5f5f5',
  },
  logoPlaceholder: {
    width: 120,
    height: 120,
    backgroundColor: '#EE436E',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 60,
    marginBottom: 32,
    shadowColor: '#EE436E',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 6,
  },
  logoText: {
    color: '#FEFEFE',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  perifareTitle: {
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 16,
    color: '#201E1E',
    letterSpacing: -0.5,
  },
  perifareText: {
    fontSize: 17,
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: 32,
    color: '#201E1E',
    opacity: 0.8,
    fontWeight: '400',
  },
  perifareSubtitle: {
    fontSize: 22,
    fontWeight: '700',
    alignSelf: 'flex-start',
    marginBottom: 20,
    color: '#EE436E',
    letterSpacing: -0.3,
  },
  perifarePoint: {
    fontSize: 16,
    lineHeight: 26,
    marginBottom: 16,
    alignSelf: 'flex-start',
    color: '#201E1E',
    paddingLeft: 8,
    opacity: 0.9,
  },
  perifareFooter: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 32,
    color: '#EE436E',
    letterSpacing: -0.2,
  },
  bold: {
    fontWeight: '700',
    color: '#EE436E',
  },
  commissionBox: {
    backgroundColor: '#FEFEFE',
    borderRadius: 16,
    padding: 24,
    marginTop: 24,
    borderWidth: 2,
    borderColor: '#FBDA25',
    shadowColor: '#201E1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  commissionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#EE436E',
    marginBottom: 8,
    letterSpacing: -0.3,
  },
  commissionText: {
    fontSize: 16,
    color: '#201E1E',
    lineHeight: 24,
    fontWeight: '400',
    opacity: 0.9,
  },
  cell: {
    flex: 1,
    textAlign: 'center',
    fontSize: 15,
    fontWeight: '600',
    color: '#201E1E',
  },
  // Premium visual elements
  premiumCard: {
    backgroundColor: '#FEFEFE',
    borderRadius: 20,
    padding: 24,
    margin: 8,
    shadowColor: '#201E1E',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    elevation: 6,
    borderWidth: 1,
    borderColor: '#f5f5f5',
  },
  luxuryText: {
    fontSize: 16,
    color: '#201E1E',
    lineHeight: 24,
    fontWeight: '400',
    opacity: 0.8,
  },
  accentText: {
    color: '#EE436E',
    fontWeight: '700',
  },

  // Perifare Diagram Styles
  diagramContainer: {
    marginTop: 24,
    marginBottom: 24,
    paddingHorizontal: 20,
  },

  // Concept Section
  conceptSection: {
    alignItems: 'center',
    marginBottom: 32,
  },
  conceptTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#201E1E',
    marginBottom: 12,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  conceptDescription: {
    fontSize: 16,
    fontWeight: '500',
    color: '#201E1E',
    opacity: 0.8,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 10,
  },

  // Problem Section
  problemSection: {
    marginBottom: 24,
  },
  problemCard: {
    backgroundColor: '#f5f5f5',
    borderRadius: 20,
    padding: 24,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    shadowColor: '#201E1E',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  problemIcon: {
    fontSize: 32,
    textAlign: 'center',
    marginBottom: 12,
    opacity: 0.8,
  },
  problemTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#d32f2f',
    textAlign: 'center',
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  problemPoints: {
    alignItems: 'flex-start',
  },
  problemPoint: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
    marginBottom: 8,
    lineHeight: 20,
  },

  // Solution Section
  solutionSection: {
    marginBottom: 24,
  },
  solutionCard: {
    backgroundColor: '#EE436E',
    borderRadius: 20,
    padding: 24,
    shadowColor: '#EE436E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  solutionIcon: {
    fontSize: 32,
    textAlign: 'center',
    marginBottom: 12,
  },
  solutionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FEFEFE',
    textAlign: 'center',
    marginBottom: 16,
    letterSpacing: 0.5,
  },
  solutionPoints: {
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  solutionPoint: {
    fontSize: 14,
    color: '#FEFEFE',
    fontWeight: '600',
    marginBottom: 8,
    lineHeight: 20,
  },
  boldText: {
    fontWeight: '800',
    color: '#FBDA25',
  },
  ctaSection: {
    backgroundColor: '#FBDA25',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  ctaText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#201E1E',
    textAlign: 'center',
  },

  // Testimonial Section
  testimonialSection: {
    backgroundColor: '#FEFEFE',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#f0f0f0',
    shadowColor: '#201E1E',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  testimonialQuote: {
    fontSize: 15,
    fontWeight: '600',
    color: '#201E1E',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 12,
    fontStyle: 'italic',
  },
  testimonialAuthor: {
    fontSize: 13,
    fontWeight: '700',
    color: '#EE436E',
    textAlign: 'center',
  },
});

export default styles;
