import { StyleSheet } from 'react-native';

const colors = {
  primary: '#EE436E',
  secondary: '#FBDA25',
  black: '#201E1E',
  white: '#FEFEFE',
  lightGray: '#F8F9FA',
  gray: '#8E8E93',
  darkGray: '#48484A',
  shadow: 'rgba(0, 0, 0, 0.1)',
};

export const modalStyles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
  },
  modalView: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 8,
    paddingHorizontal: 20,
    paddingBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 25,
    maxHeight: '85%',
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: colors.gray,
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
    opacity: 0.3,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.black,
    marginBottom: 24,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  itemContainer: {
    flexDirection: 'row',
    padding: 18,
    marginBottom: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.lightGray,
    backgroundColor: colors.white,
    alignItems: 'center',
    shadowColor: colors.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  selectedItemContainer: {
    borderColor: colors.primary,
    borderWidth: 2,
    backgroundColor: '#FFF8FA',
    shadowColor: colors.primary,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    transform: [{ scale: 1.02 }],
  },
  iconContainer: {
    marginRight: 16,
    alignItems: 'center',
    width: 50,
  },
  infoContainer: {
    flex: 1,
  },
  priceContainer: {
    alignItems: 'flex-end',
  },
  vehicleName: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.black,
    letterSpacing: -0.2,
  },
  vehicleDescription: {
    fontSize: 13,
    color: colors.gray,
    marginTop: 6,
    lineHeight: 18,
  },
  vehiclePrice: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.primary,
    letterSpacing: -0.5,
  },
  vehicleDistance: {
    fontSize: 12,
    color: colors.gray,
    marginTop: 2,
  },
  capacityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    backgroundColor: colors.lightGray,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  capacityText: {
    marginLeft: 4,
    color: colors.darkGray,
    fontSize: 12,
    fontWeight: '500',
  },
  scheduleButton: {
    backgroundColor: colors.black,
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 24,
    marginTop: 24,
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  scheduleButtonDisabled: {
    backgroundColor: colors.lightGray,
    shadowOpacity: 0,
    elevation: 0,
  },
  scheduleButtonText: {
    color: colors.white,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: -0.3,
  },
  scheduleButtonTextDisabled: {
    color: colors.gray,
  },
});
