import { StyleSheet } from 'react-native';

const colors = {
  primary: '#EE436E',
  secondary: '#FBDA25',
  white: '#FEFEFE',
  lightGray: '#F8F9FA',
  mediumGray: '#E8E8E8',
  softGray: '#F5F5F7',
  accent: '#FF6B9D',
  shadowLight: 'rgba(238, 67, 110, 0.15)',
  shadowDark: 'rgba(0, 0, 0, 0.08)',
};

export const swipeButtonStyles = StyleSheet.create({
  container: {
    backgroundColor: colors.white,
    borderRadius: 35,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    overflow: 'hidden',
    shadowColor: colors.shadowDark,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 15,
    borderWidth: 2,
    borderColor: colors.mediumGray,
  },
  text: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1.0,
    textAlign: 'center',
  },
  completedText: {
    color: colors.secondary,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 1.0,
    textAlign: 'center',
  },
  handle: {
    position: 'absolute',
    left: 8,
    height: 54,
    width: 54,
    borderRadius: 27,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.shadowLight,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.8,
    shadowRadius: 16,
    elevation: 20,
    borderWidth: 3,
    borderColor: colors.white,
  },
  handlePressed: {
    transform: [{ scale: 0.96 }],
    shadowOpacity: 1.0,
    shadowRadius: 20,
    backgroundColor: colors.accent,
  },
  progressTrack: {
    position: 'absolute',
    left: 0,
    top: 0,
    height: '100%',
    backgroundColor: colors.softGray,
    borderRadius: 35,
  },
  toastContainer: {
    position: 'absolute',
    bottom: 50,
    left: 20,
    right: 20,
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.shadowDark,
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 20,
    borderWidth: 2,
    borderColor: colors.mediumGray,
  },
  toastMessage: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '700',
    marginLeft: 15,
    letterSpacing: 0.8,
  },
});
