export const vehicleClasses = [
  {
    id: 'mini',
    name: 'Mini',
    capacity: 4,
    description: 'Quick Plans, No Chaos. Lock In Your Ride Early. Reliable Rules, Minus The Last-Minute Rush. Small Car, Big Convenience. Fair Pricing Powered By Perifare.',
    price: 1112,
    distance: 'Up to 38 Kms',
    icon: 'car-side',
  },
  {
    id: 'sedan',
    name: 'SEDAN',
    capacity: 4,
    description: 'Comfort That’s Planned, Not Improvised. Your Plans, Your Schedule—Zero Surprises. Sedan Rides Made Simple. Fair Pricing Powered By Perifare.',
    price: 1319,
    distance: 'Up to 38 Kms',
    icon: 'car-side',
  },
  {
    id: 'suv',
    name: 'SUV',
    capacity: 6,
    description: 'Room For Everyone, Plans Included. Perfect For The Crew, Booked In Advance. Spacious And Sorted, Just How You Like It.',
    price: 1457,
    distance: 'Up to 38 Kms',
    icon: 'car-side',
  },
  {
    id: 'premium_suv',
    name: 'PREMIUM_SUV',
    capacity: 6,
    description: 'For Big Groups And Bigger Plans. Premium Rides, Booked Your Way. Travel Together, Arrive Easy.',
    price: 1600,
    distance: 'Up to 38 Kms',
    icon: 'car-side',
  },
    {
    id: 'luxury',
    name: 'LUXURY',
    capacity: 4,
    description: 'The Finest Cars For The Discerning. Arrive In Style, Every Time. Unmatched Comfort, Unforgettable Experience.',
    price: 2500,
    distance: 'Up to 38 Kms',
    icon: 'car-side',
  },
];
