
export const documentConfig = [
  { key: 'dlDocument', label: 'DL Front', type: 'DL', required: true },
  { key: 'dlDocumentBack', label: 'DL Back', type: 'DL', required: true },
  { key: 'rcDocument', label: 'RC Front', type: 'RC', required: true },
  { key: 'rcDocumentBack', label: 'RC Back', type: 'RC', required: true },
  { key: 'aadhaarDocument', label: 'Aadhaar Front', type: 'Other', required: true },
  { key: 'aadhaarDocumentBack', label: 'Aadhaar Back', type: 'Other', required: true },
  { key: 'pan', label: 'PAN', type: 'Other', required: false },
  { key: 'selfi', label: 'Selfi (Clear Photo)', type: 'Other', required: true },
  { key: 'permit', label: 'Permit', type: 'Specific', required: true },
  { key: 'insuranceDocument', label: 'Insurance', type: 'Specific', required: true },
  { key: 'selfiWithvehicle', label: 'Selfie with Vehicle', type: 'agreement', required: true },
  { key: 'agreement', label: 'Lease Agreement', type: 'agreement2', required: false },
  { key: 'bankDetails', label: 'Bank Cheque / Passbook', type: 'Other', required: true },
  { key: 'vehicleFitness', label: 'Vehicle Fitness Certificate', type: 'Specific', required: true },
];

export const userModel = {
  applicationStatus: 'Conditionally Approved',
  profile: {
    firstName: 'John',
    lastName: 'Doe',
    drivingLicense: 'AB123456789',
    city: 'New York',
    vehicleType: 'Car',
    vehicleNumber: 'NY-123-456',
    manufactureName: 'Toyota',
    modelName: 'Camry',
    rcDlSameName: 'Yes',
    referralCode: 'REF123',
  },
  documents: {
    dlDocument: { uri: 'https://via.placeholder.com/150', status: 'Approved', rejectionReason: null },
    dlDocumentBack: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    rcDocument: { uri: 'https://via.placeholder.com/150', status: 'Pending', rejectionReason: null },
    rcDocumentBack: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    aadhaarDocument: { uri: 'https://via.placeholder.com/150', status: 'Rejected', rejectionReason: 'Aadhaar card is expired.' },
    aadhaarDocumentBack: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    pan: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    selfi: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    permit: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    insuranceDocument: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    selfiWithvehicle: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    agreement: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    bankDetails: { uri: null, status: 'Not Uploaded', rejectionReason: null },
    vehicleFitness: { uri: null, status: 'Not Uploaded', rejectionReason: null },
  },
};
